# Generated by Django 5.0.1 on 2024-01-16 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('is_image_maker', models.BooleanField(default=False, verbose_name='Нейросеть для изображений')),
            ],
            options={
                'verbose_name': 'Нейросеть',
                'verbose_name_plural': 'Нейросети',
            },
        ),
        migrations.CreateModel(
            name='SampleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория шаблонов',
                'verbose_name_plural': 'Категории шаблонов',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена (руб/мес)')),
                ('characteristics', models.JSONField(default=dict, verbose_name='Характеристики')),
                ('requests_per_month', models.PositiveIntegerField(verbose_name='Количество запросов в месяц')),
                ('requests_per_day', models.PositiveIntegerField(verbose_name='Количество запросов в день')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sender', models.BooleanField(default=True, verbose_name='Отправитель')),
                ('text', models.TextField(verbose_name='Текст')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Время отправки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments', verbose_name='Файл')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('categories', models.ManyToManyField(to='chat.samplecategory', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписка',
            },
        ),
    ]
