# Generated by Django 5.0.1 on 2024-01-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_is_deleted_usersample_usersampleslikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersample',
            name='categories',
            field=models.ManyToManyField(null=True, to='chat.samplecategory', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='usersample',
            name='name',
            field=models.CharField(max_length=64, null=True, verbose_name='Название'),
        ),
    ]
