# Generated by Django 5.0.1 on 2024-01-31 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_usersample_categories_usersample_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersampleslikes',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='usersample',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='usersample',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersampleslikes',
            name='user',
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.DeleteModel(
            name='UserSample',
        ),
        migrations.DeleteModel(
            name='UserSamplesLikes',
        ),
    ]
