# Generated by Django 5.0.1 on 2024-02-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_sample_usersampleslikes_usersample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AI',
        ),
        migrations.AlterField(
            model_name='sample',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
    ]
