# Generated by Django 5.0.1 on 2024-02-07 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_delete_ai_alter_sample_description_alter_sample_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Текущий чат'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='chat.message', verbose_name='Сообщение'),
        ),
    ]
