# Generated by Django 5.0.1 on 2024-02-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_message_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='requests_per_month',
        ),
        migrations.AddField(
            model_name='message',
            name='used_ai',
            field=models.CharField(blank=True, choices=[('GPT35', 'GPT-3.5'), ('GPT4', 'GPT-4'), ('SD', 'Stable Diffusion'), ('MJ', 'Midjourney'), ('DL3', 'Dall-e 3')], null=True, verbose_name='Использованная нейросеть'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='requests_DL3',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество запросов в месяц (Dall-e 3)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='requests_GPT35',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество запросов в месяц (GPT-3.5)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='requests_GPT4',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество запросов в месяц (GPT-4)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='requests_MJ',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество запросов в месяц (Midjourney)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='requests_SD',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество запросов в месяц (Stable Diffusion)'),
        ),
    ]
