# Generated by Django 5.0.1 on 2024-02-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_tariff_requests_per_month_message_used_ai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='requests_VS',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество запросов в месяц (Vision)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='used_ai',
            field=models.CharField(blank=True, choices=[('GPT35', 'GPT-3.5'), ('GPT4', 'GPT-4'), ('VS', 'Vision'), ('SD', 'Stable Diffusion'), ('MJ', 'Midjourney'), ('DL3', 'Dall-e 3')], null=True, verbose_name='Использованная нейросеть'),
        ),
    ]
