# Generated by Django 5.0.1 on 2024-02-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_tariff_requests_vs_alter_message_used_ai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='requests_per_day',
        ),
        migrations.AddField(
            model_name='tariff',
            name='samples_included',
            field=models.BooleanField(default=False, verbose_name='Подключены запросы'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='characteristics',
            field=models.JSONField(default={'details': []}, verbose_name='Характеристики (через запятую в двойных кавычках в [])'),
        ),
    ]
