# Generated by Django 5.0.1 on 2024-02-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_remove_tariff_requests_per_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='characteristics',
            field=models.JSONField(default=dict, verbose_name='Характеристики ({"details": []})'),
        ),
    ]
