# Generated by Django 5.0.1 on 2024-02-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_tariff_characteristics'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='from_subscription',
            field=models.BooleanField(default=True, verbose_name='Запрос по подписке'),
        ),
    ]
