# Generated by Django 5.0.1 on 2024-02-11 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_message_from_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.sample', verbose_name='Шаблон'),
        ),
    ]
