# Generated by Django 5.0.1 on 2024-02-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_message_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='use_context',
            field=models.BooleanField(default=True, verbose_name='Использовать контекст'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='samples_included',
            field=models.BooleanField(default=False, verbose_name='Подключены шаблоны'),
        ),
    ]
