# Generated by Django 5.0.1 on 2024-02-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_newchatcategory_newchatsample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newchatcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='new_chat_icons', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='newchatsample',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='new_chat_icons', verbose_name='Иконка'),
        ),
    ]
