# Generated by Django 5.0.1 on 2024-02-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_alter_newchatcategory_icon_alter_newchatsample_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewChatInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, verbose_name='Название')),
                ('icon', models.ImageField(upload_to='new_chat_icons', verbose_name='Иконка')),
                ('description', models.CharField(max_length=128, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Пункт туториала',
                'verbose_name_plural': 'Пункты туториала',
            },
        ),
    ]
