# Generated by Django 5.0.1 on 2024-02-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_newchatinstruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newchatcategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='newchatinstruction',
            name='icon',
        ),
    ]
