# Generated by Django 5.0.1 on 2024-02-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_newchatcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newchatsample',
            name='for_free_version',
            field=models.TextField(blank=True, null=True, verbose_name='Примеры изображений для бесплатной версии'),
        ),
    ]
