# Generated by Django 5.0.1 on 2024-02-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_newchatsample_for_free_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newchatsample',
            name='for_free_version',
            field=models.JSONField(default=dict, verbose_name='Примеры изображений для бесплатной версии'),
        ),
    ]
