# Generated by Django 5.0.1 on 2024-02-20 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_alter_newchatsample_for_free_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newchatsample',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='chat.newchatcategory', verbose_name='Категория'),
        ),
    ]
