# Generated by Django 5.0.1 on 2024-02-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_paymentoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentoperation',
            name='cost',
            field=models.FloatField(verbose_name='Сумма заказа'),
        ),
    ]
