# Generated by Django 5.0.1 on 2024-01-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_faqcategory_faq_home_page_faq_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'verbose_name': 'Категория вопросов', 'verbose_name_plural': 'Категории вопросов'},
        ),
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, upload_to='article_photos', verbose_name='Заглавное фото'),
        ),
        migrations.AddField(
            model_name='article',
            name='second_title',
            field=models.TextField(blank=True, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='main.faqcategory', verbose_name='Категории'),
        ),
    ]
