# Generated by Django 5.0.1 on 2024-01-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_faqcategory_options_article_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='business_page',
            field=models.BooleanField(default=False, verbose_name='Отображать на странице для бизнеса'),
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, to='main.articlecategory', verbose_name='Категории'),
        ),
    ]
