# Generated by Django 5.0.1 on 2024-02-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_faq_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteContent',
        ),
    ]
