# Generated by Django 5.0.1 on 2024-01-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foreign_registration',
            field=models.BooleanField(default=True, verbose_name='Зарегистрирован через стороннее приложение'),
        ),
    ]
