# Generated by Django 5.0.1 on 2024-02-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_foreign_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_ai',
            field=models.CharField(choices=[('GPT-3.5', 'GPT-3.5'), ('GPT-4', 'GPT-4')], default=('GPT-3.5', 'GPT-3.5'), max_length=256, verbose_name='Выбранная нейросеть'),
        ),
        migrations.AddField(
            model_name='user',
            name='selected_img_ai',
            field=models.CharField(choices=[('Stable Diffusion', 'Stable Diffusion'), ('Midjourney', 'Midjourney')], default=('Stable Diffusion', 'Stable Diffusion'), max_length=256, verbose_name='Выбранная нейросеть для изображений'),
        ),
    ]
