# Generated by Django 5.0.1 on 2024-02-22 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(blank=True, max_length=32, verbose_name='Промокод')),
                ('balance', models.PositiveBigIntegerField(default=0, verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Бизнес подписка',
                'verbose_name_plural': 'Бизнес подписка',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='business_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.businesssubscription', verbose_name='Бизнес подписка'),
        ),
    ]
