# Generated by Django 5.0.1 on 2024-02-23 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_businesssubscription_user_business_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='authentication.businesssubscription', verbose_name='Бизнес подписка'),
        ),
    ]
