# Generated by Django 5.0.1 on 2024-02-26 16:16

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[authentication.models.User.unique_email_validator], verbose_name='Адрес электронной почты'),
        ),
    ]
